[package]
name = "hill-cipher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
input-macro = "0.2.0"
itertools = "0.12.0"
nalgebra = "0.32.3"
rand = "0.8.5"
